### ISSUE TITLE
can this be up on colab?

### ISSUE THREAD

**Issue by GeorvityLabs** [JanaldoChen/Anim-NeRF#10]
would be great to test it out on custom videos via colab.
also , is the green screen a must?

**Comment by GeorvityLabs** [comment]
what if there is a video matting (Deep Learning based) applied as a post-processing step and then that video is fed to the network , that should work too right.

**Comment by JanaldoChen** [comment]
It's a good suggestion! I am not sure that it is suitable to make a colab for this project because the training process is time-consuming, but I can try to make a colab for the data preprocessing.

**Comment by radman-x** [comment]
@JanaldoChen : I have a Colab written for doing testing/inference from a video (including all the preprocessing required for testing). This does not include training, however. Also, need to fix a few bugs and clean it up a bit for public access - I can probably get this done within a week. Would you like me to do this?

**Comment by GeorvityLabs** [comment]
awesome , that would be great @radman-x

**Comment by JanaldoChen** [comment]
> @JanaldoChen : I have a Colab written for doing testing/inference from a video (including all the preprocessing required for testing). This does not include training, however. Also, need to fix a few bugs and clean it up a bit for public access - I can probably get this done within a week. Would you like me to do this?

Sounds great! Please pull a request after you finish it.

**Comment by GeorvityLabs** [comment]
@radman-x any updates on the colab?

**Comment by radman-x** [comment]
I tried to do a pull-request but do not have permission. I also tried a fork, branch and commit but again did not have permissions. Anyways, I'm uploading the Colab file here. @JanaldoChen -- maybe you can just commit it to the main repo
[Anim_NeRF_Colab.zip](https://github.com/JanaldoChen/Anim-NeRF/files/8028047/Anim_NeRF_Colab.zip)
.

**Comment by JanaldoChen** [comment]
> I tried to do a pull-request but do not have permission. I also tried a fork, branch and commit but again did not have permissions. Anyways, I'm uploading the Colab file here. @JanaldoChen -- maybe you can just commit it to the main repo [Anim_NeRF_Colab.zip](https://github.com/JanaldoChen/Anim-NeRF/files/8028047/Anim_NeRF_Colab.zip) .

Thanks a lot! Previously someone have successfully  made a pull request, you can try it again like this(https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork). Or can you give me the colab like?

**Comment by GeorvityLabs** [comment]
@radman-x @radman-x on running
` !python -m tools.vibe --images_folder {project_path}/data/custom/{file_basename}/cam000_masked/images --output_folder {project_path}/data/custom/{file_basename}`

an error pops up 
AssertionError: Path data/vibe_data/SMPL_NEUTRAL.pkl does not exist!

first, the vibe_data folder wasn't created , so i made a folder , then this error shows up.

**Comment by GeorvityLabs** [comment]
@radman-x could you make a video on how to use the colab notebook , like a quick (no need for voice) , short video , on how to run and config VIBE.
because it can get confusing for some folks.

**Comment by GeorvityLabs** [comment]
also just noted the #modify-vibe-config , doesn't take you anywhere. under the usage notes.

**Comment by radman-x** [comment]
@GeorvityLabs -- OK, thanks for the feedback. I think the problem with running tools.vibe is that the VIBE config.py was not modified before running the VIBE source scripts/prepare_data.sh. This may have been due to the link bug you mentioned. One problem is that if you compact a section of the notebook anything linking to the compacted section will fail. Also, I think that the state of each section in the notebook (ie, compacted vs. expanded) is saved with the (.ipynb) file so I re-saved another version with all sections expanded. Also, there was a missing link for #modify-vibe-config so I added that in. The new version (v2) of the Colab notebook is in the attached zip file. Let me know if that works or not.

As for a video, it's a good idea but not too practical since many cells in this notebook have long latency (many minutes) so I'd have to edit the video, etc. However, with all the sections now expanded and the links working, it's pretty straightforward to run the notebook -- just mount your Google drive and start working through the cells. First time notebook is opened, you need to do the "File Setup" and the "Install Dependencies Setup"; next time you run the notebook only need to run the "Install Dependencies Setup" (much quicker).

[Anim_NeRF_v2.zip](https://github.com/JanaldoChen/Anim-NeRF/files/8044100/Anim_NeRF_v2.zip)

**Comment by radman-x** [comment]
@JanaldoChen -- I tried many ways to do the pull request and all failed with "No permission" bug. If I get time next week I'll try to get the PR working. In the meantime, the file is attached in my last comment above to @GeorvityLabs (be sure to use "v2").

**Comment by JanaldoChen** [comment]
> @JanaldoChen -- I tried many ways to do the pull request and all failed with "No permission" bug. If I get time next week I'll try to get the PR working. In the meantime, the file is attached in my last comment above to @GeorvityLabs (be sure to use "v2").

Sorry for the late reply, I have uploaded the colab file provided by you.
